source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'OKAPIKit_Tests', :exclusive => true do
  pod 'OKAPIKit', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
